### ISSUE TITLE
size mismatch

### ISSUE THREAD

**Issue by puraminy** [thu-coai/PPT#6]
my server can't load t5-v1-xl, so I am trying to run the code for t5-v1 (it could be the base model)
As said I transformed it to the model suitable for the project, however when I run the code it can't load the checkpoint with size mismatch. 

```
Traceback (most recent call last):
  File "/home/pouramini/PPT/train.py", line 401, in <module>
    main()
  File "/home/pouramini/PPT/train.py", line 385, in main
    model, optimizer, lr_scheduler = setup_model_and_optimizer(args, tokenizer.vocab_size, ds_config, prompt_config)
  File "/home/pouramini/PPT/utils.py", line 190, in setup_model_and_optimizer
    args.iteration = load_checkpoint(model, optimizer, lr_scheduler, args, prompt_config)
  File "/home/pouramini/PPT/utils.py", line 330, in load_checkpoint
    model.module.load_state_dict(sd["module"], strict=False)
  File "/home/pouramini/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1604, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for EncDecModel:
	size mismatch for word_embeds.weight: copying a param with shape torch.Size([8032, 768]) from checkpoint, the shape in current model is torch.Size([32128, 768]).
	size mismatch for lm_head.weight: copying a param with shape torch.Size([8032, 768]) from checkpoint, the shape in current model is torch.Size([32128, 768]).
	size mismatch for encoder.word_embeds.weight: copying a param with shape torch.Size([8032, 768]) from checkpoint, the shape in current model is torch.Size([32128, 768]).
	size mismatch for encoder.blocks.0.self_attn.self_attn.project.weight: copying a param with shape torch.Size([576, 768]) from checkpoint, the shape in current model is torch.Size([2304, 768]).
	size mismatch for encoder.blocks.0.self_attn.self_attn.relative_attention_bias.weight: copying a param with shape torch.Size([32, 3]) from checkpoint, the shape in current model is torch.Size([32, 12]).
	size mismatch for encoder.blocks.0.self_attn.self_attn.dense.weight: copying a param with shape torch.Size([768, 192]) from checkpoint, the shape in current model is torch.Size([768, 768]).
	size mismatch for encoder.blocks.0.ff.dense_relu_dense.wi_0.weight: copying a param with shape torch.Size([512, 768]) from checkpoint, the shape in current model is torch.Size([2048, 768]).
``

**Comment by puraminy** [comment]
it seems if I don't convert it, it works

**Comment by t1101675** [comment]
Did you download the model you used from [here](https://huggingface.co/google/t5-v1_1-base) ? You need to change the configuration to this [file](https://github.com/thu-coai/PPT/blob/master/configs/model/t5_base_config.json) for the t5-v1_1-base model.
Besides, if you have only one GPU, you need to change the model parallel to 1 by setting the `--mp_size` in this [line](https://github.com/thu-coai/PPT/blob/master/tools/transform.py#L237) to 1 and `MP_SIZE` in this [line](https://github.com/thu-coai/PPT/blob/master/scripts/rte/few-shot/pt.sh#L5) to 1.
